<!--================Breadcrumb Area =================-->
<section class="breadcrumb_area br_image">
	<div class="container">
		<div class="page-cover text-center">
			<h2 class="page-cover-tittle">About Us</h2>
			<ol class="breadcrumb">
				<li><a href="index.html">Home</a></li>
				<li class="active">About</li>
			</ol>
		</div>
	</div>
</section>
<!--================Breadcrumb Area =================-->

<!--================About Area =================-->
<section class="about_area section_gap">
	<div class="container">
		<div class="section_title text-center">
			<h2>Welcome to Faith Church</h2>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from </p>
		</div>
		<div class="row">
			<div class="col-md-6 d_flex">
				<div class="about_content flex">
					<h3 class="title_color">Did not find your Package Feel free to ask us. We‘ll make it for you</h3>
					<p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.</p>
					<a href="#" class="about_btn btn_hover">Read Full Story</a>
				</div>
			</div>
			<div class="col-md-6">
				<img src="<?php echo $this->basePath() . '/uploads/image/about.jpg';?>" alt="abou_img">
			</div>
		</div>
	</div>
</section>
<!--================About Area =================-->

<!--================Features Area =================-->
<section class="features_area">
	<div class="row m0">
		<div class="col-md-3 features_item">
			<h3>Spreading Light to world</h3>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from innocence and upturning of the natural.</p>
			<a href="#" class="btn_hover view_btn">View Details</a>
		</div>
		<div class="col-md-3 features_item">
			<h3>Spreading Light to world</h3>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from innocence and upturning of the natural.</p>
			<a href="#" class="btn_hover view_btn">View Details</a>
		</div>
		<div class="col-md-3 features_item">
			<h3>Spreading Light to world</h3>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from innocence and upturning of the natural.</p>
			<a href="#" class="btn_hover view_btn">View Details</a>
		</div>
		<div class="col-md-3 features_item">
			<h3>Spreading Light to world</h3>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from innocence and upturning of the natural.</p>
			<a href="#" class="btn_hover view_btn">View Details</a>
		</div>
	</div>
</section>
<!--================Features Area =================-->

<!--================Sermons work Area =================-->
<section class="sermons_work_area section_gap">
	<div class="container">
		<div class="section_title text-center">
			<h2>Sermons This Week</h2>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from</p>
		</div>
		<div class="sermons_slider owl-carousel">
			<div class="item row">
				<div class="col-lg-8">
					<div class="sermons_image">
						<img src="<?php echo $this->basePath() . '/uploads/image/sermns.jpg';?>" alt="">
						<p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="sermons_content">
						<h3 class="title_color">Did not find your Package? Feel free to ask us. We‘ll make it for you</h3>
						<ul class="list_style sermons_category">
							<li><i class="lnr lnr-user"></i><span>Categories: </span><a href="#"> Travor James</a></li>
							<li><i class="lnr lnr-database"></i><span>Sermon Speaker: </span> Prayer</li>
							<li><i class="lnr lnr-calendar-full"></i><span>Date:</span> 5th may, 2018</li>
						</ul>
						<a href="#" class="btn_hover">View More Details</a>
					</div>
				</div>
			</div>
			<div class="item row">
				<div class="col-lg-8">
					<div class="sermons_image">
						<img src="<?php echo $this->basePath() . '/uploads/image/sermns.jpg';?>" alt="">
						<p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="sermons_content">
						<h3 class="title_color">Did not find your Package? Feel free to ask us. We‘ll make it for you</h3>
						<ul class="list_style sermons_category">
							<li><i class="lnr lnr-user"></i><span>Categories: </span><a href="#"> Travor James</a></li>
							<li><i class="lnr lnr-database"></i><span>Sermon Speaker: </span> Prayer</li>
							<li><i class="lnr lnr-calendar-full"></i><span>Date:</span> 5th may, 2018</li>
						</ul>
						<a href="#" class="btn_hover">View More Details</a>
					</div>
				</div>
			</div>
			<div class="item row">
				<div class="col-lg-8">
					<div class="sermons_image">
						<img src="<?php echo $this->basePath() . '/uploads/image/sermns.jpg';?>" alt="">
						<p>inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.</p>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="sermons_content">
						<h3 class="title_color">Did not find your Package? Feel free to ask us. We‘ll make it for you</h3>
						<ul class="list_style sermons_category">
							<li><i class="lnr lnr-user"></i><span>Categories: </span><a href="#"> Travor James</a></li>
							<li><i class="lnr lnr-database"></i><span>Sermon Speaker: </span> Prayer</li>
							<li><i class="lnr lnr-calendar-full"></i><span>Date:</span> 5th may, 2018</li>
						</ul>
						<a href="#" class="btn_hover btn_hover_two">View More Details</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================Sermons work Area=================-->

<!--================Team Area=================-->
<section class="team_area section_gap">
	<div class="container">
		<div class="section_title text-center">
			<h2>Sermons This Week</h2>
			<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from</p>
		</div>
		<div class="row mb_30">
			<div class="col-md-3 col-sm-6">
				<div class="team_item">
					<div class="team_img">
						<img src="<?php echo $this->basePath() . '/uploads/image/team1.jpg';?>" alt="team">
						<ul class="list_style">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<div class="content">
						<h3>Philip Goodwin</h3>
						<p>Chief Pastor</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="team_item">
					<div class="team_img">
						<img src="<?php echo $this->basePath() . '/uploads/image/team2.jpg';?>" alt="team">
						<ul class="list_style">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<div class="content">
						<h3>Duane Lewis</h3>
						<p>Chief Pastor</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="team_item">
					<div class="team_img">
						<img src="<?php echo $this->basePath() . '/uploads/image/team3.jpg';?>" alt="team">
						<ul class="list_style">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<div class="content">
						<h3>Jose Austin</h3>
						<p>Chief Pastor</p>
					</div>
				</div>
			</div>
			<div class="col-md-3 col-sm-6">
				<div class="team_item">
					<div class="team_img">
						<img src="<?php echo $this->basePath() . '/uploads/image/team5.jpg';?>" alt="team">
						<ul class="list_style">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
						</ul>
					</div>
					<div class="content">
						<h3>Leroy Lopez</h3>
						<p>Chief Pastor</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================Team Area=================-->

<!--================Donate Area=================-->
<section class="donate_area">
	<div class="container">
		<div class="row">
			<div class="col-md-6 d-flex align-self-center">
				<div class="donate_content ">
					<h2>Your donation can save <br>many lives</h2>
					<p>The French Revolution constituted for the conscience of the dominant aristocratic class a fall from innocence.</p>
				</div>
			</div>
			<div class="col-md-6">
				<div class="donation_form">
					<h3>How much would you like to donate?</h3>
					<div class="form-group">
						<input type='text' class="form-control" placeholder="$5" />
					</div>
					<div class="form-group">
						<input type='text' class="form-control" placeholder="$5" />
					</div>
					<div class="form-group">
						<input type='text' class="form-control" placeholder="$5" />
					</div>
					<div class="form-group">
						<select class="wide">
							<option data-display="Any">Any</option>
							<option value="1">Old</option>
							<option value="2">Younger</option>
							<option value="3">Potato</option>
						</select>
					</div>
					<a href="#" class="btn_hover btn_hover_two">Donate Now</a>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================Donate Area=================-->

<!--================Event Blog Area=================-->
<section class="event_blog_area section_gap">
	<div class="container">
		<div class="section_title text-center">
			<h2>Upcoming Events</h2>
			<p>We all live in an age that belongs to the young at heart. Life that is becoming extremely fast</p>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="event_post">
					<img src="<?php echo $this->basePath() . '/uploads/image/blog1.jpg';?>" alt="">
					<a href="#">
						<h2 class="event_title">Spreading Peace to world</h2>
					</a>
					<ul class="list_style sermons_category">
						<li><i class="lnr lnr-user"></i>Saturday, 5th may, 2018</li>
						<li><i class="lnr lnr-apartment"></i>Rocky beach Church</li>
						<li><i class="lnr lnr-location"></i>Santa monica, Los Angeles, USA</li>
					</ul>
					<a href="#" class="btn_hover">View Details</a>
				</div>
			</div>
			<div class="col-md-4">
				<div class="event_post">
					<img src="<?php echo $this->basePath() . '/uploads/image/blog2.jpg';?>" alt="">
					<a href="#">
						<h2 class="event_title">Spreading Peace to world</h2>
					</a>
					<ul class="list_style sermons_category">
						<li><i class="lnr lnr-user"></i>Saturday, 5th may, 2018</li>
						<li><i class="lnr lnr-apartment"></i>Rocky beach Church</li>
						<li><i class="lnr lnr-location"></i>Santa monica, Los Angeles, USA</li>
					</ul>
					<a href="#" class="btn_hover">View Details</a>
				</div>
			</div>
			<div class="col-md-4">
				<div class="event_post">
					<img src="<?php echo $this->basePath() . '/uploads/image/blog3.jpg';?>" alt="">
					<a href="#">
						<h2 class="event_title">Spreading Light to world</h2>
					</a>
					<ul class="list_style sermons_category">
						<li><i class="lnr lnr-user"></i>Saturday, 5th may, 2018</li>
						<li><i class="lnr lnr-apartment"></i>Rocky beach Church</li>
						<li><i class="lnr lnr-location"></i>Santa monica, Los Angeles, USA</li>
					</ul>
					<a href="#" class="btn_hover">View Details</a>
				</div>
			</div>
		</div>
	</div>
</section>
<!--================Blog Area=================-->