        <aside id="sidebar" class="sidebar right">
            <div id="vce_posts_widget-5" class="widget vce_posts_widget"><h4 class="widget-title">SLMTA Song</h4>
                <iframe width="100%" height="150" src="http://www.youtube.com/embed/lH_q5i_ncYw?showinfo=0;controls=0" frameborder="0" allowfullscreen></iframe>
            </div>
            <div id="vce_posts_widget-5" class="widget vce_posts_widget vce-sticky"><h4 class="widget-title">Featured Events</h4>
                <ul class="vce-post-slider">
                    <li>
                        <a href="#" class="featured_image_sidebar" ><span class="vce-post-img"><img width="380" height="260" src="<?php echo $this->basePath('/images/DSC_0042.JPG'); ?>" class="attachment-vce-fa-grid wp-post-image" alt="unsplash_52bf2bb8d2dd0_1 (1)" /></span></a>
                        <div class="vce-posts-wrap">
                        <a href="#203" class="vce-post-link">SLMTA event X</a>
                        </div>
                    </li>
                    <li>
                        <a href="#169" class="featured_image_sidebar" title="What Will Natural Beauty Be Like In 100 Years?"><span class="vce-post-img"><img width="380" height="260" src="<?php echo $this->basePath('/images/DSC_0088.JPG'); ?>" class="attachment-vce-fa-grid wp-post-image" alt="girl-flowers (1)" /></span></a>
                        <div class="vce-posts-wrap">
                        <a href="#169" class="vce-post-link">SLMTA Event in Uganda</a>
                        </div>
                    </li>
                    <li>
                        <a href="#153" class="featured_image_sidebar"><span class="vce-post-img"><img width="380" height="260" src="<?php echo $this->basePath('/images/DSC_0044.JPG'); ?>" class="attachment-vce-fa-grid wp-post-image" alt="voice_21" /></span></a>
                        <div class="vce-posts-wrap">
                        <a href="#153" class="vce-post-link">ASLM Meet</a>
                        </div>
                    </li>
                </ul>
            </div>
        </aside>