<?php
use Zend\Session\Container;
$sessionLogin = new Container('credo');
?>
<div class="bg-body-light">
     <div class="content content-full">
          <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
               <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Role Details</h1>
               <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                         <a href="<?php echo $this->url('admin-role', array('action' => 'index')); ?>"><li class="breadcrumb-item">Role</li></a>
                         <li class="breadcrumb-item active" aria-current="page">&nbsp;&nbsp;/ Add</li>
                    </ol>
               </nav>
          </div>
     </div>
</div>

<div class="content">

     <div class="block block-rounded block-bordered">
          <div class="block-header block-header-default">
               <h3 class="block-title">Add New Role</h3>
          </div>
          <div class="block-content">
               <div class="col-lg-12 col-xl-12">
                    <form name="addRoleInformation" id="addRoleInformation"  class="mb-5" action="<?php echo $this->url('admin-role', array('action' => 'add')); ?>" method="post">
                         <div class="form-group row">
                              <label class="col-sm-2 col-form-label" for="roleName">Role Name <span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" title="Please Enter the Role Name" class="form-control isRequired" id="roleName" name="roleName" placeholder="Enter role name" onblur="checkNameValidation('roles', 'role_name', this,null, 'The role name that you entered already exists. Please try another name..');">
                              </div>
                              <label class="col-sm-2 col-form-label" for="roleCode">Role Code <span class="mandatory">*</span></label>
                              <div class="col-sm-4">
                                   <input type="text" title="Please Enter the Role Code" class="form-control isRequired" id="roleCode" name="roleCode" placeholder="Enter role code" onblur="checkNameValidation('roles', 'role_code', this,null, 'The role code that you entered already exists. Please try another code..');">
                              </div>
                         </div>
                         <div class="form-group row">
                              <label class="col-sm-2 col-form-label" for="roleDescription">Role Description</label>
                              <div class="col-sm-4">
                                   <textarea placeholder="Enter the description" title="Please enter the description" class="form-control" id="roleDescription" name="roleDescription"></textarea>
                              </div>
                              <label class="col-sm-2 col-form-label" for="roleStatus">Status</label>
                              <div class="col-sm-4">
                                   <select class="form-control isRequired" id="roleStatus" name="roleStatus">
                                        <option value="active">Active</option>
                                        <option value="inactive">Inactive</option>
                                   </select>
                              </div>
                         </div>
                         <br>
                         <div class="form-group row" style=" padding: 10px; border: 1px solid #ff000038; ">
                              <label class="col-md-2 control-label mandatory">Note:</label>
                              <div class="col-md-10">
                                   <p class="form-control-static mandatory">Unless you choose "access" the people belonging to this role will not be able to access other rights like "add", "edit" etc.</p>
                              </div>
                         </div>
                         <fieldset>
                              <div style="padding-left:134px;" class="form-group row">
                                   <div class="custom-control custom-switch  custom-control-lg">
                                      <input type="checkbox" class="custom-control-input " id="cekAllPrivileges" name="cekUnCekAll">
                                      <label class="custom-control-label" id="selectlabel" for="cekAllPrivileges">Select All</label>
                                   </div>
                              </div>

                              <table  class="table table-striped table-hover responsive-utilities jambo_table table-responsive">
                                   <?php $pCount = 1;
                                   foreach ($resourceResult as $value) {
                                        echo "<tr class=''>";
                                        echo "<td><strong>" . ucwords($value['display_name']) . "</strong></td>";

                                        foreach ($value['privilege'] as $privilege)
                                        {
                                             echo "<td>";

                                             echo '<div  style="padding-left:10px;" class="form-group row">
                                                       <div class="custom-control custom-switch  custom-control-lg">
                                                       <input type="checkbox" class="custom-control-input cekAll" id="cekAllPrivileges'.$pCount.'"  name= "resourceName[' . $value["resource_id"] . ']['.$privilege["privilege_name"].']'.'" value="allow" onclick="updateAccess('.$pCount.')" >
                                                       <input type="hidden" class="custom-control-input setValue" id="cekAllPrivilegesResource'.$pCount.'"  name= "resource['. $value["resource_id"] . ']['. $privilege["privilege_name"].']'.'"  value="deny" >
                                                       <label class="custom-control-label" id="selectlabel" for="cekAllPrivileges'.$pCount.'">' . ucwords($privilege['display_name']) . '</label>
                                                       </div>
                                                  </div>';
                                             echo "</td>";
                                             $pCount++;
                                        }
                                             echo "</tr>";
                                   }
                                   ?>
                              </table>
                         </fieldset>

                         <div class="row items-push">
                              <div class="col-lg-7 offset-lg-4">
                                   <a href="<?php echo $this->url('admin-role', array('action' => 'index')); ?>" class="btn btn-hero-dark">Cancel</a>&nbsp;
                                   <button type="submit" class="btn btn-hero-primary" onclick="validateNow();return false;">
                                   <i class="fa fa-fw fa-check"></i> Submit
                              </div>
                         </div>
                    </form>
               </div>
          </div>
     </div>
</div>
<script type="text/javascript">

     var checked=false;
     $(function() {
          $(document).on('click', '#cekAllPrivileges', function() {
               if (!checked) {
                    $('.cekAll').prop('checked', true);
                    $(".setValue").val('allow');
                    checked=true;
                    $('#selectlabel').text('Unselect All');
               } else {
                    $('.cekAll').prop('checked', false);
                    checked=false;
                    $(".setValue").val('deny');
                    $('#selectlabel').text('Select All');
               }
          });
     });

     duplicateName = true;
     function validateNow() {

          flag = deforayValidator.init({
               formId: 'addRoleInformation'
          });
          if (flag) {
               if (duplicateName) {
                    $.blockUI();
                    document.getElementById('addRoleInformation').submit();
               }
          }
     }

     function checkNameValidation(tableName, fieldName, obj, fnct, msg){
          checkValue = document.getElementById(obj.id).value;
          var loggedCompanyId=$("#companyId").val();
          if($.trim(checkValue)!= ''){
               $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {tableName: tableName, fieldName: fieldName, value: checkValue, companyId:loggedCompanyId,fnct: fnct},
               function(data) {
                    if (data > 0)
                    {
                         Dashmix.helpers('notify', {type: 'danger', icon: 'fa fa-times mr-1', message: msg});
                         duplicateName = false;
                         document.getElementById(obj.id).value = "";
                    }
                    else {
                         duplicateName = true;
                    }
               });
          }
     }
     function updateAccess(count)
     {
        if($("#cekAllPrivileges"+count). prop("checked") == true){
            $("#cekAllPrivilegesResource"+count).val('allow');
        }else{
            $("#cekAllPrivilegesResource"+count).val('deny');
        }
     }


</script>