<?php

use Zend\Session\Container;

$sessionLogin = new Container('user');
$role = $sessionLogin->roleCode;

$acl = $this->layout()->acl;
if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\Role', 'edit')) {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center",bSortable:false}';
} else {
    $editAction = ' {"sClass":"center"},{"sClass":"center"},{"sClass":"center"},{"sClass":"center"}';
}
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Roles</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <?php if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\Role', 'add')) { ?>
                        <a href="<?php echo $this->url('admin-role', array('action' => 'add')); ?>" class="btn btn-hero-primary pull-right" style="margin-top:-5px;"><i class="fa fa-plus"></i>&nbsp;Add New Role</a>
                        <?php } ?>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">

        </div>
        <div class="block-content block-content-full">
            <table id="userDataTable" class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th>Role Name</th>
                        <th>Role Code</th>
                        <th>Role Description</th>
                        <th>Status</th>
                        <?php if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\User', 'edit')) { ?>
                        <th>Action</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5" class="dataTables_empty">Loading data from server</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    $(document).ready(function() {
        oTable = $('#userDataTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                <?php echo $editAction; ?>
            ],
            "sAjaxSource": "<?php echo $this->url('admin-role', array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    });
</script>