
<!-- CONTENT 
	============================================= -->
	<div class="content">
		<div class="container layout" style="min-height:300px;">
			
                <h1><?php echo $this->translate('A 404 error occurred') ?></h1>
                <h2>Sorry. We were unable to find the page or document you were looking for.</h2>

		</div>
	</div>
	<!-- END CONTENT 
	============================================= -->
