<?php

use Zend\Session\Container;

$container = new Container('alert');
$sessionLogin = new Container('user');
$role = $sessionLogin->roleCode;
$acl = $this->layout()->acl;
$adminMenu = "";
if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\Role', 'index')) {
    $adminMenu .= "<li id='admin-role'><a href=" . $this->url('admin-role', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i>Roles</a></li>";
}
if (isset($acl) && $acl->isAllowed($role, 'Admin\Controller\User', 'index')) {
    $adminMenu .= "<li id='admin-user'><a href=" . $this->url('admin-user', array('action' => 'index')) . "><i class='fa fa-angle-double-right'></i>Users</a></li>";
}
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>IMMANUEL CHARCH</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Daterangepicker css -->
    <link rel="icon" href="<?php echo $this->basePath() . '/uploads/image/favicon.png'; ?>" type="image/png">
    <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/plugins/daterangepicker/daterangepicker.css' ?>">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" media="all" type="text/css" href="https://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'assest/img/favicon.ico'))
        ->prependStylesheet("//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css")
        ->prependStylesheet($this->basePath() . '/assets/css/jquery-ui-timepicker-addon.css')
        ->prependStylesheet($this->basePath() . '/assets/css/deforayModal.css')
        ->prependStylesheet($this->basePath() . '/assets/css/adminstyle.css')
        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
        ->prependStylesheet($this->basePath() . '/assets/css/AdminLTE.css')
        ->prependStylesheet($this->basePath() . '/assets/css/ionicons.min.css')
        ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/assets/css/select2.css');
    ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
</head>

<body class="skin-blue">
    <!-- header logo: style can be found in header.less -->
    <header class="header dontPrint">
        <a href="<?php echo $this->url('admin-home'); ?>" class="logo">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            IMMANUEL CHARCH
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top dontPrint" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-user"></i>
                            Admin <span><i class="caret"></i></span>
                        </a>
                        <ul class="dropdown-menu" style=" width: auto; ">
                            <!-- User image -->
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <!--    <div class="pull-left">-->
                                <!--        <a href="< ?php echo $this->url('admin-employee', array('action' => 'change-password')); ?>" class="btn btn-default btn-flat">Change Password</a>-->
                                <!--    </div>-->
                                <div class="text-center">
                                    <a href="<?php echo $this->url('admin-login', array('action' => 'logout')); ?>" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->

        <aside class="left-side sidebar-offcanvas dontPrint">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li id="admin-dashboard">
                        <a href="<?php echo $this->url('admin-home'); ?>">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        </a>
                    </li>
                    <li id="admin" class="treeview">
                        <a href="javascript:void(0);">
                            <i class="fa fa-cogs"></i>
                            <span>Admin</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <?php echo $adminMenu; ?>
                        </ul>
                    </li>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <?php echo $this->content; ?>
            <?php echo (isset($this->aclError) ? $this->aclError : ""); ?>
        </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->

    <div id="dDiv" class="dialog">
        <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div>
        <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0'>some problem</iframe>
    </div>
    <!-- add new calendar event modal -->
    <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <?php
    echo $this->headScript()
        ->prependFile($this->basePath() . '/assets/js/deforayValidation.js')
        ->prependFile($this->basePath() . '/assets/js/deforayModal.js')
        ->prependFile($this->basePath() . '/assets/js/jquery.blockUI.js')
        ->prependFile($this->basePath() . '/assets/js/AdminLTE/dashboard.js')
        ->prependFile($this->basePath() . '/assets/js/AdminLTE/app.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/jqueryKnob/jquery.knob.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/sparkline/jquery.sparkline.min.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/daterangepicker/daterangepicker.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/datatables/dataTables.bootstrap.js')
        ->prependFile($this->basePath() . '/assets/js/plugins/datatables/jquery.dataTables.js')
        ->prependFile($this->basePath() . '/assets/js/select2.min.js')
        ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/assets/js/jquery-ui.1.10.4.min.js')
    ?>

    <?php echo $this->inlineScript() ?>
    <script src="<?php echo $this->basePath() . '/assets/plugins/daterangepicker/daterangepicker.js' ?>"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script type="text/javascript">
        str = $(location).attr('pathname');
        splitsUrl = str.split("/", 4);
        if (splitsUrl.length > 2 && splitsUrl[1] == "admin") {
            if (splitsUrl[2] == "role") {
                $("#admin").addClass("active");
                $("#admin-role").addClass("active");
            } else if (splitsUrl[2] == "user") {
                $("#admin").addClass("active");
                $("#admin-user").addClass("active");
            }
        }
        $(document).ready(function() {
            <?php
            if (isset($container->alertMsg) && $container->alertMsg != "") {
                ?>
            alert("<?php echo $container->alertMsg; ?>");
            <?php
                $container->alertMsg = "";
                unset($container->alertMsg);
            }
            ?>
        });

        $(".checkNum").keydown(function(e) {
            // Allow: backspace, delete, tab, escape, enter and .
            if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                // Allow: Ctrl+A
                (e.keyCode == 65 && e.ctrlKey === true) ||
                // Allow: home, end, left, right
                (e.keyCode >= 35 && e.keyCode <= 39)) {
                // let it happen, don't do anything
                return;
            }
            // Ensure that it is a number and stop the keypress
            if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                e.preventDefault();
            }
        });

        function showModal(url, w, h) {
            showdefModal('dDiv', w, h);
            document.getElementById('dFrame').style.height = h + 'px';
            document.getElementById('dFrame').style.width = w + 'px';
            document.getElementById('dFrame').src = url;
        }

        function closeModal() {
            document.getElementById('dFrame').src = "";
            hidedefModal('dDiv');
        }
    </script>
</body>

</html>