<?php
use Zend\Session\Container;
echo $this->doctype();
?>
<!DOCTYPE html>
<html>
    <head>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . 'assest/img/favicon.ico'))
                ->prependStylesheet("//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css")
                ->prependStylesheet($this->basePath() . '/assets/css/deforayModal.css')
                ->prependStylesheet($this->basePath() . '/assets/css/style.css');
        ?>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/js/base64_decode.js')
                ->prependFile($this->basePath() . '/assets/js/base64_encode.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.blockUI.js')
                ->prependFile($this->basePath() . '/assets/js/deforayValidation.js')
                ->prependFile($this->basePath() . '/assets/js/jquery-ui.1.10.4.min.js');
            ?>
    </head>
    <body style="background:#fff !important;">
        <?php echo $this->content; ?>
    </body>
</html>
