<?php
    use Zend\Session\Container;
    $sessionLogin = new Container('user');
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Customer</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <a href="<?php echo $this->url('admin-customer', array('action' => 'index')); ?>">
                        <li class="breadcrumb-item">Customer Details</li>
                    </a>
                    <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Edit</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Customer Details</h3>
        </div>
        <div class="block-content">
            <form name="customerInformation" id="customerInformation" class="mb-5" action="<?php echo $this->url('admin-customer', array('action' => 'edit')); ?>" method="post">
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="firstName">First name<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['first_name'];?>" class="form-control isRequired" id="firstName" name="firstName" placeholder="Enter the first name" title="Please enter the first name">
                        <input type="hidden" id="customerId" name="customerId" value="<?php echo base64_encode($customerResult['customer_id']);?>">
                    </div>
                    <label class="col-sm-2 col-form-label" for="lastName">Last name<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['last_name'];?>" class="form-control isRequired" id="lastName" name="lastName" placeholder="Enter the last name" title="Please enter the last name"/>
                    </div>

                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="email">Email<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="email" value="<?php echo $customerResult['email'];?>" class="form-control isEmail isRequired" id="email" name="email" placeholder="Enter the email" title="Please enter the valid email" onblur="checkNameValidation('customer', 'email', this, '<?php echo "customer_id##" . $customerResult->customer_id; ?>', 'Entered email id exist . Please enter an another email id.')">
                    </div>
                    <label class="col-sm-2 col-form-label" for="gender">Gender</label>
                    <div class="col-sm-4" style=" display: inline-flex; ">
                        <div class="custom-control custom-radio custom-control-primary mb-1" style="padding-right: 20px;">
                            <input type="radio" class="custom-control-input" id="male" value="male" name="gender" checked title="Please select the gender" <?php echo ($customerResult['gender'] == 'male')?'checked':'';?>>
                            <label class="custom-control-label" for="male">Male</label>
                        </div>
                        <div class="custom-control custom-radio custom-control-primary mb-1">
                            <input type="radio" class="custom-control-input" id="female" value="female" name="gender" title="Please select the gender" <?php echo ($customerResult['gender'] == 'female')?'checked':'';?>>
                            <label class="custom-control-label" for="female">Female</label>
                        </div>
                    </div>
                </div>
                
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="mobileNumber">Mobile No<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="number" value="<?php echo $customerResult['phone'];?>" class="form-control isMobile isRequired" id="mobileNumber" name="mobileNumber" placeholder="Enter the mobile" title="Please enter the 10 digit valid mobile" onblur="checkNameValidation('customer', 'phone', this, '<?php echo "customer_id##" . $customerResult->customer_id; ?>', 'Entered phone no exist . Please enter an another phone no.')">
                    </div>
                    <label class="col-sm-2 col-form-label" for="alternateNumber">Alternate Mobile No</label>
                    <div class="col-sm-4">
                        <input type="number" value="<?php echo $customerResult['alternate_phone'];?>" class="form-control isMobile" id="alternateNumber" name="alternateNumber" placeholder="Enter the alternate mobile" title="Please enter the valid 10 digit alternate mobile no">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="receiverName">Receiver Name</label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['recceiver_name'];?>" class="form-control isMobile" id="receiverName" name="receiverName" placeholder="Enter the receiver name" title="Please enter the receiver name">
                    </div>
                    <label class="col-sm-2 col-form-label" for="paymentStatus">Payment Status</label>
                    <div class="col-sm-4">
                        <select class="form-control" id="paymentStatus" name="paymentStatus" title="Please select the payment status">
                            <option value="">--Select--</option>
                            <option value="pending" <?php echo ($customerResult['payment_status'] == 'pending')?'selected="selected"':'';?>>Pending</option>
                            <option value="processing" <?php echo ($customerResult['payment_status'] == 'processing')?'selected="selected"':'';?>>Processing</option>
                            <option value="completed" <?php echo ($customerResult['payment_status'] == 'completed')?'selected="selected"':'';?>>Completed</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="address">Street Address<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['street_address'];?>" class="form-control isRequired" id="address" name="address" placeholder="Enter the street address" title="Please enter the street address">
                    </div>
                    <label class="col-sm-2 col-form-label" for="address2">Address Line 2<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['address_line2'];?>" class="form-control isRequired" id="address2" name="address2" placeholder="Enter the address line 2" title="Please enter the address line 2">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="city">City<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['city'];?>" class="form-control isRequired" id="city" name="city" placeholder="Enter the city" title="Please enter the city">
                    </div>
                    <label class="col-sm-2 col-form-label" for="state">State<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="js-select2 form-control isRequired" class="form-control isRequired" id="state" name="state" data-placeholder="Choose one state.." title="Please select the state">
                            <option value="">--Select--</option>
                            <?php foreach($stateResult as $state){ ?>
                            <option value="<?php echo base64_encode($state['state_id']);?>" <?php echo ($customerResult['state'] == $state['state_id'])?'selected="selected"':'';?>><?php echo ucwords($state['state_name']);?></option>
                            <?php }?>
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="pincode">Pincode<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['pincode'];?>" class="form-control isPincode isRequired" id="pincode" name="pincode" placeholder="Enter the valid 6 digit pincode" title="Please enter the valid 6 digit pincode">
                    </div>
                    <label class="col-sm-2 col-form-label" for="churchName">Church Name<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $customerResult['church_name'];?>" class="form-control isRequired" id="churchName" name="churchName" placeholder="Enter the church name" title="Please enter the church name">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="customerStatus">Status<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control isRequired" id="customerStatus" name="customerStatus" title="Please select the customer status">
                            <option value="">--Select--</option>
                            <option value="active" <?php echo ($customerResult['customer_status'] == 'active')?'selected="selected"':'';?>>Active</option>
                            <option value="inactive" <?php echo ($customerResult['customer_status'] == 'active')?'selected="selected"':'';?>>Inactive</option>
                        </select>
                    </div>
                </div>
                <div class="row items-push submit">
                    <div class="col-lg-7 offset-lg-4">
                        <a href="<?php echo $this->url('admin-customer', array('action' => 'index')); ?>" class="btn btn-hero-dark">Cancel</a>&nbsp;
                        <button type="submit" class="btn btn-hero-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'customerInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('customerInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                tableName: tableName,
                fieldName: fieldName,
                value: checkValue,
                fnct: fnct
            },
            function(data) {
                if (data > 0) {
                    alert(msg,'err');
                    duplicateName = false;
                    document.getElementById(obj.id).value = "";
                } else {
                    duplicateName = true;
                }
            });
        }
    }
</script>