<?php
use Zend\Session\Container;
use Application\Service\CommonService;

$common = new CommonService();
$bsUserLogincontainer = new Container('bsUserLoginContainer');

// \Zend\Debug\Debug::dump($preResult);
// \Zend\Debug\Debug::dump($postResult);
// \Zend\Debug\Debug::dump($configResult);
// \Zend\Debug\Debug::dump($testResult);
//  die;

$maxQuestion = $preResult['maxQuestion'];    

?>

<style type="text/css">
div.table-title {
  display: block;
  margin: auto;
  max-width: 600px;
  padding:5px;
  width: 100%;
}

.table-title h3 {
   color: #fafafa;
   font-size: 30px;
   font-weight: 400;
   font-style:normal;
   font-family: "Roboto", helvetica, arial, sans-serif;
   text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
   text-transform:uppercase;
}


/*** Table Styles **/
.table-fill:hover{
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
    border-style: groove;
}
.table-fill {
    border-style: groove;
    border-color: #EAEAEA;
    border-width: 1px;
    margin-top: 30px !important;
    background: white;
    border-radius:3px;
    border-collapse: collapse;
    height: 320px;
    margin: auto;
    padding:5px;
    width: 100%;
    animation: float 5s infinite;
}
 
th {
    color: #343a45;
    background: #F1F1F1;
    border-bottom: 1px solid #e34735;
    font-size: 23px;
    font-weight: 100;
    padding: 24px;
    text-align: center;
    vertical-align: middle;
}

th:first-child {
  border-top-left-radius:3px;
}
 
th:last-child {
  border-top-right-radius:3px;
  border-right:none;
}
  
tr {
  border-top: 1px solid #C1C3D1;
  border-bottom-: 1px solid #C1C3D1;
  color:#666B85;
  font-size:16px;
  font-weight:normal;
  text-shadow: 0 1px 1px rgba(256, 256, 256, 0.1);
}
 
/* tr:hover td {
  background:#4E5066;
  color:#FFFFFF;
  border-top: 1px solid #22262e;
} */
 
tr:first-child {
  border-top:none;
}

tr:last-child {
  border-bottom:none;
}
 
tr:nth-child(odd) td {
  background:#EBEBEB;
}
 
/* tr:nth-child(odd):hover td {
  background:#4E5066;
} */

tr:last-child td:first-child {
  border-bottom-left-radius:3px;
}
 
tr:last-child td:last-child {
  border-bottom-right-radius:3px;
}
 
td {
    padding: 20px;
    vertical-align: middle;
    font-weight: 300;
    font-size: 18px;
    border-right: 1px solid #C1C3D1;
}

td:last-child {
  border-right: 0px;
}

th.text-left {
  text-align: left;
}

th.text-center {
  text-align: center;
}

th.text-right {
  text-align: right;
}

td.text-left {
  text-align: left;
}

td.text-center {
  text-align: center;
}

td.text-right {
  text-align: right;
}
td.text-left.titile {
    width: 20%;
    text-transform: capitalize;
    font-weight: 600;
}
.certificate{
    padding:20px;
    border: 2px solid #DCDCDC;
    background: #F1F1F1;
    margin-bottom: 10px;
}
</style>
<!-- TITLE BAR
	============================================= -->
<div class="b-titlebar content" style="padding-top:0px;padding-bottom:0px;border-bottom:1px solid #E4E4E4;">
    <div class="container layout"  style="padding-top:0px;padding-bottom:0px;">
        <!-- Title -->
        <h1>Certificate</h1>
    </div>
</div>
<!-- END TITLE BAR
============================================= -->
<div class="container layout" >
    <?php
		echo $this->partial('partial/biosafety');
	?>
    <div class="certificate">
    <?php $count = 1;
    foreach($testResult as $test){ 
        if((isset($test['pretest_end_datetime']) && trim($test['pretest_end_datetime'])!="0000-00-00 00:00:00") && (trim($test['pretest_end_datetime'])!=NULL)){ ?>
            <table  class="table-fill">
                <thead>
                    <tr>
                        <th colspan="2">
                            <?php
                                if($count == 1){
                                    echo "Attempt 1";
                                }else{
                                    echo "Attempt  ".$count;
                                }
                            ?>
                        </th>
                    </tr>
                </thead>
                <tbody class="table-hover">
                    <tr>
                        <td class="text-left titile">
                            Pre Test Date
                        </td>
                        <td class="text-left ">
                            <?php 
                                if((isset($test['pretest_end_datetime']) && trim($test['pretest_end_datetime'])!="0000-00-00 00:00:00") && (trim($test['pretest_end_datetime'])!=NULL)){
                                    $preTestDate = explode(" ",$test['pretest_end_datetime']);
                                    echo $common->humanDateFormat($preTestDate[0]);
                                }else{
                                    echo "You have not completed Pre Test.";
                                }
                            ?>
                        </td>
                    <tr>
                        <td class="text-left titile">
                            Pre Test Score
                        </td>
                        <td class="text-left">
                            <?php
                            if(isset($test['pre_test_score']) && trim($test['pre_test_score'])!=""){
                                $preScore = ($test['pre_test_score'] / $maxQuestion);
                                $preTotal = round($preScore * 100);
                                echo $preTotal; 
                            }else{
                                echo "You have not completed the Pre Test.";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left titile">
                            Post Test Date
                        </td>
                        <td class="text-left">
                            <?php
                                if((isset($test['posttest_end_datetime']) && trim($test['posttest_end_datetime'])!="0000-00-00 00:00:00") && (trim($test['posttest_end_datetime'])!=NULL)){ 
                                    $postTestDate = explode(" ",$test['posttest_end_datetime']);
                                    echo $common->humanDateFormat($postTestDate[0]);
                                }else{
                                    echo "You have not completed the Post Test.";
                                }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left titile">
                            Post Test Score
                        </td>
                        <td class="text-left">
                            <?php
                            if(isset($test['post_test_score']) && trim($test['post_test_score'])!=""){
                                $postScore = ($test['post_test_score'] / $maxQuestion);
                                $postTotal = round($postScore * 100);
                                echo $postTotal; 
                            }else{
                                echo "You have not completed the Post Test.";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="text-left titile">
                            Certificate
                        </td>
                        <td class="text-left">
                            <?php 
                                if($test['user_test_status']=='pass'){ ?>
                                    <a href="/biosafety/pdf?testId=<?php echo base64_encode($test['test_id']); ?>" target="_blank" class="btn big colored" style="width: auto;align-content: center;margin: auto;">Download Certificate</a>
                                <?php }else{
                                    echo "The minimum score required to pass the test is ".$configResult['0']['test_config_value'];
                                }
                            ?>
                        </td>
                    </tr>
                </tbody>
            </table>
    <?php 
        }
    $count++; } ?>
    </div>
</div>
