<link rel="stylesheet"  type="text/css" href="<?php echo $this->basePath().'/assets/css/AdminLTE.css';?>"/>
<link rel="stylesheet"  type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"/>
<link rel="stylesheet"  type="text/css" href="<?php echo $this->basePath().'/assets/css/star-rating.css';?>"/>
<style type="text/css">
    html,body{
        background:#fff !important;
    }
    .star-rating{
        width:420px !important;
    }
    .rating-md {
       font-size: 2.03em !important;
    }
    .label {
        padding-top:5px !important;
        font-weight:600 !important;
        letter-spacing:0.6px;
    }
    .star-rating .caption {
        padding-left: 5px;
    }
    .star-rating-rtl .caption {
        padding-right: 5px;
    }
    .clear-rating{
        padding-top:3px;
    }
    .rating-stars{
        margin-right:2px;
        margin-left:2px;
    }
</style>
<!-- Content Header (Page header) -->
<section class="content-header" style="padding-left:18px;">
    <h4>Package Review (<?php echo ucwords($pkgData['pkResult'][0]['package_name']); ?>)</h4>
</section>
<!-- Main content -->
<section class="content" style="background:#fff !important;">
            <div class="box-header">
                <div class="pull-right" style="font-size:15px;padding-right:28%;"><span class="mandatory">*</span> indicates required field &nbsp;</div> 
            </div><!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" name="packageReview" id="packageReview"  method="post" action="<?php echo $this->url('package-review'); ?>" autocomplete="off">
                <div class="box-body">
                    <div class="form-group">
                        <label for="reviewText" class="col-lg-2 control-label">Review <span class="mandatory">*</span></label>
                        <div class="col-lg-4">
                            <input type="hidden" name="packageAgentMapId" id="packageAgentMapId" value="<?php echo base64_encode($packageAgentMapId); ?>"/>
                            <textarea class="form-control isRequired" name="reviewText" id="reviewText" placeholder="Type Review" title="Please type your review to continue" style="width:420px;max-width:420px;height:106px !important;max-height:106px;"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="rating" class="col-lg-2 control-label"><div style="padding-top:4px;">Rating</div></label>
                        <div class="col-lg-4">
                            <input type="number" class="rating" name="packgeRating" id="packgeRating"/>
                        </div>
                    </div>
                    <div class="box-footer" style="padding-left:18%;">
                        <input type="button" class="btn btn-primary btn-sm" value="Submit" onclick="validateNow();return false;">
                    </div>
                </div>
         </form>
</section><!-- /.content -->
<script type="text/javascript" src="<?php echo $this->basePath().'/assets/js/star-rating.js';?>"></script>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'packageReview'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('packageReview').submit();
            }
        }
    }
</script>